declare class DrapoContextItem {
    private _context;
    private _parent;
    private _children;
    private _data;
    private _dataKey;
    private _key;
    private _iterator;
    private _index;
    private _element;
    private _elementForTemplate;
    private _elementOld;
    get Context(): DrapoContext;
    get Parent(): DrapoContextItem;
    get Children(): DrapoContextItem[];
    get Data(): any;
    set Data(value: any);
    get DataKey(): string;
    set DataKey(value: string);
    get Key(): string;
    set Key(value: string);
    get Iterator(): string;
    set Iterator(value: string);
    get Index(): number;
    set Index(value: number);
    get Element(): HTMLElement;
    set Element(value: HTMLElement);
    get ElementForTemplate(): HTMLElement;
    set ElementForTemplate(value: HTMLElement);
    get ElementOld(): HTMLElement;
    set ElementOld(value: HTMLElement);
    get RootItem(): DrapoContextItem;
    get RootElement(): HTMLElement;
    constructor(context: DrapoContext, parent?: DrapoContextItem);
    GetAbsolute(mustachePart: string): string[];
}
