declare class DrapoViewport {
    private _el;
    private _elScroll;
    private _elBallonBefore;
    private _elBallonAfter;
    private _heightScroll;
    private _heightBefore;
    private _heightAfter;
    private _heightItem;
    private _heightBallonBefore;
    private _heightBallonAfter;
    private _dataStart;
    private _dataEnd;
    private _dataLength;
    private _factor;
    private _eventScrollTimeout;
    get Element(): HTMLElement;
    set Element(value: HTMLElement);
    get ElementBallonBefore(): HTMLElement;
    set ElementBallonBefore(value: HTMLElement);
    get ElementBallonAfter(): HTMLElement;
    set ElementBallonAfter(value: HTMLElement);
    get ElementScroll(): HTMLElement;
    set ElementScroll(value: HTMLElement);
    get HeightScroll(): number;
    set HeightScroll(value: number);
    get HeightBefore(): number;
    set HeightBefore(value: number);
    get HeightAfter(): number;
    set HeightAfter(value: number);
    get HeightItem(): number;
    set HeightItem(value: number);
    get HeightBallonBefore(): number;
    set HeightBallonBefore(value: number);
    get HeightBallonAfter(): number;
    set HeightBallonAfter(value: number);
    get DataStart(): number;
    set DataStart(value: number);
    get DataEnd(): number;
    set DataEnd(value: number);
    get DataLength(): number;
    set DataLength(value: number);
    get Factor(): number;
    set Factor(value: number);
    get EventScrollTimeout(): number;
    set EventScrollTimeout(value: number);
}
